//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackEnd.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DiseaseDBEntities : DbContext
    {
        public DiseaseDBEntities()
            : base("name=DiseaseDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AdditionalInfo> AdditionalInfoes { get; set; }
        public virtual DbSet<Illness> Illnesses { get; set; }
        public virtual DbSet<IllnessType> IllnessTypes { get; set; }
        public virtual DbSet<Medication> Medications { get; set; }
        public virtual DbSet<MedicationType> MedicationTypes { get; set; }
        public virtual DbSet<RiskFactor> RiskFactors { get; set; }
        public virtual DbSet<RiskFactorType> RiskFactorTypes { get; set; }
        public virtual DbSet<Symptom> Symptoms { get; set; }
        public virtual DbSet<SymptomType> SymptomTypes { get; set; }
        public virtual DbSet<Treatment> Treatments { get; set; }
        public virtual DbSet<TreatmentType> TreatmentTypes { get; set; }
    }
}
