//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackEnd.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Illness
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Illness()
        {
            this.Symptoms = new HashSet<Symptom>();
        }
    
        public int IllnessID { get; set; }
        public Nullable<int> RF_ID { get; set; }
        public Nullable<int> IllnessTypeID { get; set; }
        public Nullable<int> TreatmentID { get; set; }
        public Nullable<int> AdditionalInfoID { get; set; }
    
        public virtual AdditionalInfo AdditionalInfo { get; set; }
        public virtual IllnessType IllnessType { get; set; }
        public virtual RiskFactor RiskFactor { get; set; }
        public virtual Treatment Treatment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Symptom> Symptoms { get; set; }
    }
}
